### PR TITLE
FISH-438 Updated maven cargo plugin

### PR DESCRIPTION
**Pull request by Cousjava**

### CODE REVIEW

**Review by MattGill98 — COMMENTED** [review]
What's wrong with https://github.com/payara/Payara_PatchedProjects/pull/359?

**Comment by dmatej** [comment]
Is it worth? Wouldn't be better to create a PR to the original repo and ask for the release? Or use temporary release in Nexus if we need it ASAP?
Seems the release cadency is good:
https://github.com/codehaus-cargo/cargo/releases

**Comment by Cousjava** [comment]
@MattGill98 It didn't have a Jira number

**Comment by lprimak** [comment]
This needs to go to payara artifacts repo, if still necessary

**Pull request closed without merging**
