### PR TITLE
FISH-196 EJB injection in stateless resource in ear

### PR DESCRIPTION
**Pull request by Cousjava**
Jersey version 2.30.payara-p3

Also includes a further fix for APPSERV-61 and some upstream test fixes.

Jersey PR is payara/patched-src-jersey#67

### CODE REVIEW

**Comment by pzygielo** [comment]
I'm getting checksums different than declared in corresponding file for some files.
For example
```
b424b25d1a2b1980312a65ea3d7c566af2e0b9de
64794726d5e5bc5af9b0a2fdbeed6e4c0aa8ff51 org/glassfish/hk2/xml-configuration-example/2.6.1.payara-p3/xml-configuration-example-2.6.1.payara-p3.pom
```
or
```
c74d0626d5aaf598bb90d0b4617565f6
618bccfea4352e9e21599ff539732d0b org/glassfish/hk2/security-lockdown-example-system/2.6.1.payara-p3/security-lockdown-example-system-2.6.1.payara-p3.pom
```

**Comment by Cousjava** [comment]
@pzygielo I have checked for some files in this PR and the checksums in this one are correct. i.e.

```
curl --silent https://raw.githubusercontent.com/payara/Payara_PatchedProjects/82ee239716ebaec786d6080db93cdeab6ead2e72/org/glassfish/jersey/connectors/jersey-netty-connector/2.30.payara-p3/jersey-netty-connector-2.30.payara-p3.pom | sha1sum
1584742b8ab7272ad42cd725090942586e96b278  -
```
```
curl --silent https://raw.githubusercontent.com/payara/Payara_PatchedProjects/82ee239716ebaec786d6080db93cdeab6ead2e72/org/glassfish/jersey/connectors/jersey-netty-connector/2.30.payara-p3/jersey-netty-connector-2.30.payara-p3.pom.sha1
1584742b8ab7272ad42cd725090942586e96b278
```

**Comment by pzygielo** [comment]
> @pzygielo I have checked for some files 

And I did for all of them.

> in this PR and the checksums in this one are correct. i.e.

I wrote _for some_, which I meant, that _for others_ checksums *are* correct. Using the one I gave as example I got:
```
curl --silent https://raw.githubusercontent.com/payara/Payara_PatchedProjects/82ee239716ebaec786d6080db93cdeab6ead2e72/org/glassfish/hk2/xml-configuration-example/2.6.1.payara-p3/xml-configuration-example-2.6.1.payara-p3.pom | sha1sum
64794726d5e5bc5af9b0a2fdbeed6e4c0aa8ff51  -
curl          https://raw.githubusercontent.com/payara/Payara_PatchedProjects/82ee239716ebaec786d6080db93cdeab6ead2e72/org/glassfish/hk2/xml-configuration-example/2.6.1.payara-p3/xml-configuration-example-2.6.1.payara-p3.pom.sha1
b424b25d1a2b1980312a65ea3d7c566af2e0b9de
```

Do you get different result for _that one_?
If you don't - do you need the list of all 74 files I find troubling?

**Comment by Cousjava** [comment]
I do get different results for that one, but that isn't a file I have updated in this PR. I'm checking that there aren't any new problems in this PR, and create a new one to fix the problems with other checksums.

**Comment by pzygielo** [comment]
> I do get different results for that one, but that isn't a file I have updated in this PR.
> I'm checking that there aren't any new problems in this PR.

Understood. And you are right - this PR is checksums-fine.
I'm sorry for the noise.

**Review by Pandrex247 — APPROVED** [review]

**Pull request merged**
