### PR TITLE
PAYARA-4122 HK2 Patch

### PR DESCRIPTION
**Pull request by Cousjava**
For all streams.

Fix for OSGi lock issue.

### CODE REVIEW

**Comment by dmatej** [comment]
Can I add something to the same version? (2.6.1.payara-p1) ... to avoid releasing p2 ... I need the second PR to join :)

**Comment by Cousjava** [comment]
@dmatej  yes

**Comment by MattGill98** [comment]
I'm sorry to wade in but I'm bumping the priority of this, and since your PR is failing tests I'm going to merge this in. Sorry to be a nuisance!

**Comment by dmatej** [comment]
> since your PR is failing tests 
It doesn't, but never mind ...

**Comment by dmatej** [comment]
Linked PR merged in this version: https://github.com/payara/patched-src-hk2/pull/8

**Pull request merged**
