### PR TITLE
Payara issue 200 - SSO sync throws NoSuchMethodError

### PR DESCRIPTION
**Pull request by Pandrex247**
Added patched shoal from dmatej

### CODE REVIEW

**Comment by smillidge** [comment]
Why is 1.6.51-SNAPSHOT in there as well?

**Comment by Pandrex247** [comment]
Because I sloppily just copied my entire shoal repo over, my bad

**Comment by Pandrex247** [comment]
Still builds ok with the old versions removed, so should be good to merge unless you want to run further tests

**Comment by smillidge** [comment]
You can merge it in. I assume there's a corresponding pull request to reference this version form either the nucleus or appserver poms?

**Comment by Pandrex247** [comment]
It's sat in a branch on my own fork to test it works against the main Payara-PatchedProjects repo, I'll quickly test it and create a pull request if it works.

**Pull request merged**
